using System.Speech.Recognition;
using KTANERoboExpert.Uncertain;

namespace KTANERoboExpert.Modules;

public class Jukebox : RoboExpertModule
{
    public override string Name => "Jukebox";
    public override string Help => "Forever Edge Love";
    private Grammar? _grammar;
    public override Grammar Grammar => _grammar ??= new(new GrammarBuilder(new Choices([.. _lyrics.SelectMany(x => x)]), 3, 3));

    public override void ProcessCommand(string command)
    {
        var words = command.Split(' ');
        var songs = _lyrics.Where(a => words.All(a.Contains)).ToArray();
        if (songs.Length is not 1)
        {
            Speak("Pardon?");
            return;
        }

        Speak(songs[0].Where(words.Contains).Conjoin());
        ExitSubmenu();
        Solve();
    }

    private static readonly string[][] _lyrics = [
        [
            "Time",
            "Place",
            "What",
            "Thing",
            "Builds",
            "Dreams",
            "Slips",
            "Away",
        ],
        [
            "Change",
            "Mind",
            "Honey",
            "Still",
            "Free",
            "Take",
            "Me",
        ],
        [
            "Lover's",
            "Humour",
            "Funeral",
            "Knows",
            "Everybody's",
            "Should",
            "Have",
            "Sooner",
        ],
        [
            "We're",
            "Talking",
            "Away",
            "Don't",
            "Know",
            "Anyway",
        ],
        [
            "Hear",
            "Drums",
            "Tonight",
            "Hears",
            "Quiet",
            "Conversation",
        ],
        [
            "Less",
            "Conversation",
            "More",
            "Action",
            "Please",
            "Aggravation",
            "Satisfaction",
            "Me",
        ],
        [
            "Standing",
            "Edge",
            "Forever",
            "Start",
            "Whatever",
            "Shouting",
            "Love",
            "World",
        ],
        [
            "All",
            "Things",
            "True",
            "Care",
            "Truth",
            "Brings",
            "Take",
            "Ride",
            "Trip",
        ],
        [
            "Don't",
            "Care",
            "Monday's",
            "Blue",
            "Grey",
            "Wednesday",
        ],
        [
            "There's",
            "Need",
            "Feel",
            "Down",
            "Yourself",
            "Ground",
        ],
        [
            "Leave",
            "Tomorrow",
            "Still",
            "Remember",
            "Travelling",
            "Many",
            "Places",
            "See",
        ],
        [
            "Hole",
            "Logic",
            "Know",
            "Answers",
            "Claim",
            "Science",
            "Magic",
            "Buy",
        ],
        [
            "Crossed",
            "Deserts",
            "Miles",
            "Swam",
            "Water",
            "Searching",
            "Piece",
            "Something",
        ],
        [
            "Heard",
            "Sound",
            "Walls",
            "Came",
            "Down",
            "Thinking",
            "You",
        ],
        [
            "Time",
            "Side",
            "End",
            "Beautiful",
            "Thing",
            "Spend",
        ],
        [
            "Something",
            "Giving",
            "You",
            "One",
            "Want",
        ],
        [
            "Give",
            "Hand",
            "Then",
            "Hello",
            "Hardly",
            "Speak",
            "Heart",
        ],
        [
            "Hello",
            "Me",
            "Wondering",
            "After",
            "Years",
            "Meet",
        ],
        [
            "Place",
            "Heart",
            "Know",
            "Love",
            "Could",
            "Much",
            "Brighter",
            "Tomorrow",
        ],
        [
            "Knows",
            "Tomorrow",
            "Brings",
            "World",
            "Few",
            "Hearts",
            "Survive",
        ],
        [
            "Hear",
            "People",
            "Sing",
            "Songs",
            "Men",
            "Music",
            "Will",
            "Again",
        ],
        [
            "Need",
            "More",
            "Dreams",
            "Less",
            "Life",
            "Dark",
            "Light",
        ],
        [
            "Found",
            "Love",
            "Me",
            "Darling",
            "Dive",
            "Right",
            "Follow",
            "Lead",
        ],
        [
            "Nobody",
            "Tell",
            "There's",
            "One",
            "Song",
            "Singing",
        ],
        [
            "Step",
            "One",
            "Need",
            "Talk",
            "Walks",
            "Sit",
            "Down",
        ],
    ];
}
