namespace KTANERoboExpert.Modules;

public partial class ModuleMaze
{
    private static readonly Dictionary<string, string> _abbreviations = new()
    {
        ["101 Dalmatians"] = "101 Dalmatians",
        ["3D Maze"] = "3D Maze",
        ["3D Tunnels"] = "3D Tunnels",
        ["aa"] = "aa",
        ["needy aa"] = "aa",
        ["alfa alfa"] = "aa",
        ["needy alfa alfa"] = "aa",
        ["Accumulation"] = "Accumulation",
        ["Adjacent Letters"] = "Adjacent Letters",
        ["Adventure Game"] = "Adventure Game",
        ["Air Traffic Controller"] = "Air Traffic Controller",
        ["needy Air Traffic Controller"] = "Air Traffic Controller",
        ["Alchemy"] = "Alchemy",
        ["Algebra"] = "Algebra",
        ["Alpha"] = "Alpha",
        ["needy Alpha"] = "Alpha",
        ["Alphabet"] = "Alphabet",
        ["Alphabet Numbers"] = "Alphabet Numbers",
        ["Alphabetical Order"] = "Alphabetical Order",
        ["needy Alphabetical Order"] = "Alphabetical Order",
        ["Anagrams"] = "Anagrams",
        ["Answering Questions"] = "Answering Questions",
        ["needy Answering Questions"] = "Answering Questions",
        ["Astrology"] = "Astrology",
        ["Backgrounds"] = "Backgrounds",
        ["Bartending"] = "Bartending",
        ["Bases"] = "Bases",
        ["Battleship"] = "Battleship",
        ["Benedict Cumberbatch"] = "Benedict Cumberbatch",
        ["Big Circle"] = "Big Circle",
        ["Binary LEDs"] = "Binary LEDs",
        ["Binary Puzzle"] = "Binary Puzzle",
        ["Binary Tree"] = "Binary Tree",
        ["Bitmaps"] = "Bitmaps",
        ["Bitwise Operations"] = "Bitwise Operations",
        ["Black Hole"] = "Black Hole",
        ["Blackjack"] = "Blackjack",
        ["Blind Alley"] = "Blind Alley",
        ["Blind Maze"] = "Blind Maze",
        ["Blockbusters"] = "Blockbusters",
        ["Boggle"] = "Boggle",
        ["Boolean Maze"] = "Boolean Maze",
        ["Boolean Venn Diagram"] = "Boolean Venn Diagram",
        ["Braille"] = "Braille",
        ["British Slang"] = "British Slang",
        ["Broken Buttons"] = "Broken Buttons",
        ["Broken Guitar Chords"] = "Broken Guitar Chords",
        ["The Bulb"] = "The Bulb",
        ["Burger Alarm"] = "Burger Alarm",
        ["Burglar Alarm"] = "Burglar Alarm",
        ["The Button"] = "The Button",
        ["Button"] = "The Button",
        ["Button Masher"] = "Button Masher",
        ["needy Button Masher"] = "Button Masher",
        ["Button Sequence"] = "Button Sequence",
        ["Caesar Cipher"] = "Caesar Cipher",
        ["Calendar"] = "Calendar",
        ["Capacitor Discharge"] = "Capacitor Discharge",
        ["needy Capacitor Discharge"] = "Capacitor Discharge",
        ["Catchphrase"] = "Catchphrase",
        ["Challenge & Contact"] = "Challenge & Contact",
        ["Character Shift"] = "Character Shift",
        ["Cheap Checkout"] = "Cheap Checkout",
        ["Chess"] = "Chess",
        ["Chord Qualities"] = "Chord Qualities",
        ["Christmas Presents"] = "Christmas Presents",
        ["The Clock"] = "The Clock",
        ["Clock"] = "The Clock",
        ["The Code"] = "The Code",
        ["Code"] = "The Code",
        ["Coffeebucks"] = "Coffeebucks",
        ["Color Decoding"] = "Color Decoding",
        ["Color Generator"] = "Color Generator",
        ["Color Match"] = "Color Match",
        ["needy Color Match"] = "Color Match",
        ["Color Math"] = "Color Math",
        ["Color Morse"] = "Color Morse",
        ["Colored Keys"] = "Colored Keys",
        ["Colored Squares"] = "Colored Squares",
        ["Colored Switches"] = "Colored Switches",
        ["Colorful Insanity"] = "Colorful Insanity",
        ["Colorful Madness"] = "Colorful Madness",
        ["Colour Flash"] = "Colour Flash",
        ["Combination Lock"] = "Combination Lock",
        ["Command Prompt"] = "Command Prompt",
        ["needy Command Prompt"] = "Command Prompt",
        ["Complex Keypad"] = "Complex Keypad",
        ["Complicated Buttons"] = "Complicated Buttons",
        ["Complicated Wires"] = "Complicated Wires",
        ["Connection Check"] = "Connection Check",
        ["Connection Device"] = "Connection Device",
        ["Cookie Jars"] = "Cookie Jars",
        ["Cooking"] = "Cooking",
        ["Coordinates"] = "Coordinates",
        ["Countdown"] = "Countdown",
        ["Crackbox"] = "Crackbox",
        ["Crazy Talk"] = "Crazy Talk",
        ["Creation"] = "Creation",
        ["Cruel Countdown"] = "Cruel Countdown",
        ["Cruel Piano Keys"] = "Cruel Piano Keys",
        ["Cryptography"] = "Cryptography",
        ["The Crystal Maze"] = "The Crystal Maze",
        ["Crystal Maze"] = "The Crystal Maze",
        ["The Cube"] = "The Cube",
        ["Cube"] = "The Cube",
        ["Curriculum"] = "Curriculum",
        ["Cursed Double-Oh"] = "Cursed Double-Oh",
        ["Decolored Squares"] = "Decolored Squares",
        ["Determinants"] = "Determinants",
        ["needy Determinants"] = "Determinants",
        ["DetoNATO"] = "DetoNATO",
        ["Deto NATO"] = "DetoNATO",
        ["The Digit"] = "The Digit",
        ["Digit"] = "The Digit",
        ["Digit String"] = "Digit String",
        ["Digital Cipher"] = "Digital Cipher",
        ["Digital Root"] = "Digital Root",
        ["Discolored Squares"] = "Discolored Squares",
        ["Divided Squares"] = "Divided Squares",
        ["Dominoes"] = "Dominoes",
        ["Double Color"] = "Double Color",
        ["Double-Oh"] = "Double-Oh",
        ["Dr. Doctor"] = "Dr. Doctor",
        ["Dragon Energy"] = "Dragon Energy",
        ["Draw"] = "Draw",
        ["needy Draw"] = "Draw",
        ["Edgework"] = "Edgework",
        ["needy Edgework"] = "Edgework",
        ["Elder Futhark"] = "Elder Futhark",
        ["Emoji Math"] = "Emoji Math",
        ["Encrypted Morse"] = "Encrypted Morse",
        ["English Test"] = "English Test",
        ["Equations"] = "Equations",
        ["Error Codes"] = "Error Codes",
        ["European Travel"] = "European Travel",
        ["Extended Password"] = "Extended Password",
        ["Factory Maze"] = "Factory Maze",
        ["Fast Math"] = "Fast Math",
        ["Faulty Backgrounds"] = "Faulty Backgrounds",
        ["The Festive Jukebox"] = "The Festive Jukebox",
        ["Festive Jukebox"] = "The Festive Jukebox",
        ["Festive Piano Keys"] = "Festive Piano Keys",
        ["The Fidget Spinner"] = "The Fidget Spinner",
        ["Fidget Spinner"] = "The Fidget Spinner",
        ["needy Fidget Spinner"] = "The Fidget Spinner",
        ["Filibuster"] = "Filibuster",
        ["needy Filibuster"] = "Filibuster",
        ["FizzBuzz"] = "FizzBuzz",
        ["Flags"] = "Flags",
        ["Flashing Lights"] = "Flashing Lights",
        ["Flavor Text"] = "Flavor Text",
        ["Flavor Text EX"] = "Flavor Text EX",
        ["Flip The Coin"] = "Flip The Coin",
        ["needy Flip The Coin"] = "Flip The Coin",
        ["Follow the Leader"] = "Follow the Leader",
        ["Font Select"] = "Font Select",
        ["Foreign Exchange Rates"] = "Foreign Exchange Rates",
        ["Forget Everything"] = "Forget Everything",
        ["Forget Me Not"] = "Forget Me Not",
        ["Forget This"] = "Forget This",
        ["Four-Card Monte"] = "Four-Card Monte",
        ["Free Parking"] = "Free Parking",
        ["Friendship"] = "Friendship",
        ["Functions"] = "Functions",
        ["Gadgetron Vendor"] = "Gadgetron Vendor",
        ["Game of Life Cruel"] = "Game of Life Cruel",
        ["Cruel Game of Life"] = "Game of Life Cruel",
        ["Game of Life Simple"] = "Game of Life Simple",
        ["Simple Game of Life"] = "Game of Life Simple",
        ["The Gamepad"] = "The Gamepad",
        ["Gamepad"] = "The Gamepad",
        ["Genetic Sequence"] = "Genetic Sequence",
        ["The Giant's Drink"] = "The Giant's Drink",
        ["Giant's Drink"] = "The Giant's Drink",
        ["Graffiti Numbers"] = "Graffiti Numbers",
        ["Graphic Memory"] = "Graphic Memory",
        ["Greek Calculus"] = "Greek Calculus",
        ["Grid Matching"] = "Grid Matching",
        ["Gridlock"] = "Gridlock",
        ["Grocery Store"] = "Grocery Store",
        ["Guitar Chords"] = "Guitar Chords",
        ["The Hangover"] = "The Hangover",
        ["Hangover"] = "The Hangover",
        ["Harmony Sequence"] = "Harmony Sequence",
        ["Hex To Decimal"] = "Hex To Decimal",
        ["needy Hex To Decimal"] = "Hex To Decimal",
        ["The Hexabutton"] = "The Hexabutton",
        ["Hexabutton"] = "The Hexabutton",
        ["Hexamaze"] = "Hexamaze",
        ["Hidden Colors"] = "Hidden Colors",
        ["Hieroglyphics"] = "Hieroglyphics",
        ["Hogwarts"] = "Hogwarts",
        ["Homophones"] = "Homophones",
        ["Horrible Memory"] = "Horrible Memory",
        ["Hot Potato"] = "Hot Potato",
        ["needy Hot Potato"] = "Hot Potato",
        ["HTTP Response"] = "HTTP Response",
        ["needy HTTP Response"] = "HTTP Response",
        ["Human Resources"] = "Human Resources",
        ["Hunting"] = "Hunting",
        ["The Hypercube"] = "The Hypercube",
        ["Hypercube"] = "The Hypercube",
        ["Ice Cream"] = "Ice Cream",
        ["Identity Parade"] = "Identity Parade",
        ["IKEA"] = "IKEA",
        ["Instructions"] = "Instructions",
        ["The iPhone"] = "The iPhone",
        ["iPhone"] = "The iPhone",
        ["The Jack-O'-Lantern"] = "The Jack-O'-Lantern",
        ["Jack-O-Lantern"] = "The Jack-O'-Lantern",
        ["The Jewel Vault"] = "The Jewel Vault",
        ["Jewel Vault"] = "The Jewel Vault",
        ["The Jukebox"] = "The Jukebox",
        ["Jukebox"] = "The Jukebox",
        ["Keypad"] = "Keypad",
        ["Knob"] = "Knob",
        ["needy Knob"] = "Knob",
        ["Know Your Way"] = "Know Your Way",
        ["Krazy Talk"] = "Krazy Talk",
        ["Kudosudoku"] = "Kudosudoku",
        ["The Labyrinth"] = "The Labyrinth",
        ["Labyrinth"] = "The Labyrinth",
        ["Lasers"] = "Lasers",
        ["Laundry"] = "Laundry",
        ["LED Encryption"] = "LED Encryption",
        ["LED Grid"] = "LED Grid",
        ["LED Math"] = "LED Math",
        ["Left and Right"] = "Left and Right",
        ["LEGOs"] = "LEGOs",
        ["Letter Keys"] = "Letter Keys",
        ["Light Cycle"] = "Light Cycle",
        ["Lights Out"] = "Lights Out",
        ["needy Lights Out"] = "Lights Out",
        ["Lightspeed"] = "Lightspeed",
        ["Lion's Share"] = "Lion's Share",
        ["Listening"] = "Listening",
        ["Logic"] = "Logic",
        ["Logic Gates"] = "Logic Gates",
        ["Logical Buttons"] = "Logical Buttons",
        ["Lombax Cubes"] = "Lombax Cubes",
        ["The London Underground"] = "The London Underground",
        ["London Underground"] = "The London Underground",
        ["Mad Memory"] = "Mad Memory",
        ["Mafia"] = "Mafia",
        ["Mahjong"] = "Mahjong",
        ["Maintenance"] = "Maintenance",
        ["Manometers"] = "Manometers",
        ["Marble Tumble"] = "Marble Tumble",
        ["Maritime Flags"] = "Maritime Flags",
        ["Mashematics"] = "Mashematics",
        ["Mastermind Cruel"] = "Mastermind Cruel",
        ["Cruel Mastermind"] = "Mastermind Cruel",
        ["Mastermind Simple"] = "Mastermind Simple",
        ["Simple Mastermind"] = "Mastermind Simple",
        ["Math"] = "Math",
        ["needy Math"] = "Math",
        ["Maze"] = "Maze",
        ["Maze Scrambler"] = "Maze Scrambler",
        ["Mega Man 2"] = "Mega Man 2",
        ["Melody Sequencer"] = "Melody Sequencer",
        ["Memory"] = "Memory",
        ["Microcontroller"] = "Microcontroller",
        ["Micro-Modules"] = "Micro-Modules",
        ["Mineseeker"] = "Mineseeker",
        ["Minesweeper"] = "Minesweeper",
        ["Modern Cipher"] = "Modern Cipher",
        ["Module Homework"] = "Module Homework",
        ["Module Maze"] = "Module Maze",
        ["Modules Against Humanity"] = "Modules Against Humanity",
        ["Modulo"] = "Modulo",
        ["Monsplode Trading Cards"] = "Monsplode Trading Cards",
        ["Monsplode, Fight!"] = "Monsplode, Fight!",
        ["The Moon"] = "The Moon",
        ["Moon"] = "The Moon",
        ["Morse Code"] = "Morse Code",
        ["Morse Identification"] = "Morse Identification",
        ["needy Morse Identification"] = "Morse Identification",
        ["Morse War"] = "Morse War",
        ["Morse-A-Maze"] = "Morse-A-Maze",
        ["Morsematics"] = "Morsematics",
        ["Mortal Kombat"] = "Mortal Kombat",
        ["Motion Sense"] = "Motion Sense",
        ["needy Motion Sense"] = "Motion Sense",
        ["Mouse In The Maze"] = "Mouse In The Maze",
        ["Murder"] = "Murder",
        ["Mystic Square"] = "Mystic Square",
        ["The Necronomicon"] = "The Necronomicon",
        ["Necronomicon"] = "The Necronomicon",
        ["Needy Mrs Bob"] = "Needy Mrs Bob",
        ["Neutralization"] = "Neutralization",
        ["Nonogram"] = "Nonogram",
        ["The Number"] = "The Number",
        ["Number"] = "The Number",
        ["The Number Cipher"] = "The Number Cipher",
        ["Number Cipher"] = "The Number Cipher",
        ["Number Nimbleness"] = "Number Nimbleness",
        ["Number Pad"] = "Number Pad",
        ["Numbers"] = "Numbers",
        ["Only Connect"] = "Only Connect",
        ["Orientation Cube"] = "Orientation Cube",
        ["Painting"] = "Painting",
        ["Party Time"] = "Party Time",
        ["Passport Control"] = "Passport Control",
        ["Password"] = "Password",
        ["Pattern Cube"] = "Pattern Cube",
        ["Pay Respects"] = "Pay Respects",
        ["needy Pay Respects"] = "Pay Respects",
        ["Periodic Table"] = "Periodic Table",
        ["Perplexing Wires"] = "Perplexing Wires",
        ["Perspective Pegs"] = "Perspective Pegs",
        ["Piano Keys"] = "Piano Keys",
        ["Pie"] = "Pie",
        ["Pigpen Rotations"] = "Pigpen Rotations",
        ["Planets"] = "Planets",
        ["Playfair Cipher"] = "Playfair Cipher",
        ["Plumbing"] = "Plumbing",
        ["The Plunger"] = "The Plunger",
        ["Plunger"] = "The Plunger",
        ["needy Plunger"] = "The Plunger",
        ["The Plunger Button"] = "The Plunger Button",
        ["Plunger Button"] = "The Plunger Button",
        ["Poetry"] = "Poetry",
        ["Point of Order"] = "Point of Order",
        ["Poker"] = "Poker",
        ["Polyhedral Maze"] = "Polyhedral Maze",
        ["Press X"] = "Press X",
        ["Probing"] = "Probing",
        ["Purgatory"] = "Purgatory",
        ["QR Code"] = "QR Code",
        ["needy QR Code"] = "QR Code",
        ["Question Mark"] = "Question Mark",
        ["Quintuples"] = "Quintuples",
        ["Quiz Buzz"] = "Quiz Buzz",
        ["Radiator"] = "Radiator",
        ["The Radio"] = "The Radio",
        ["Radio"] = "The Radio",
        ["Random Number Generator"] = "Random Number Generator",
        ["needy Random Number Generator"] = "Random Number Generator",
        ["Rapid Buttons"] = "Rapid Buttons",
        ["needy Rapid Buttons"] = "Rapid Buttons",
        ["Refill that Beer!"] = "Refill that Beer!",
        ["needy Refill that Beer!"] = "Refill that Beer!",
        ["Beer"] = "Refill that Beer!",
        ["needy Beer"] = "Refill that Beer!",
        ["Regular Crazy Talk"] = "Regular Crazy Talk",
        ["Resistors"] = "Resistors",
        ["Retirement"] = "Retirement",
        ["Reverse Morse"] = "Reverse Morse",
        ["Rhythms"] = "Rhythms",
        ["Rock-Paper-Scissors-Lizard-Spock"] = "Rock Paper Scissors Lizard Spock",
        ["RPSLS"] = "Rock Paper Scissors Lizard Spock",
        ["Rotary Phone"] = "Rotary Phone",
        ["needy Rotary Phone"] = "Rotary Phone",
        ["Round Keypad"] = "Round Keypad",
        ["Rubik's Clock"] = "Rubik's Clock",
        ["Rubik's Cube"] = "Rubik's Cube",
        ["S.E.T."] = "S.E.T.",
        ["SET"] = "S.E.T.",
        ["Safety Safe"] = "Safety Safe",
        ["Schlag den Bomb"] = "Schlag den Bomb",
        ["The Screw"] = "The Screw",
        ["Screw"] = "The Screw",
        ["Scripting"] = "Scripting",
        ["Sea Shells"] = "Sea Shells",
        ["Semaphore"] = "Semaphore",
        ["Seven Wires"] = "Seven Wires",
        ["Shape Memory"] = "Shape Memory",
        ["Shape Shift"] = "Shape Shift",
        ["Shapes And Bombs"] = "Shapes And Bombs",
        ["Shikaku"] = "Shikaku",
        ["Signals"] = "Signals",
        ["Silly Slots"] = "Silly Slots",
        ["Simon Samples"] = "Simon Samples",
        ["Simon Says"] = "Simon Says",
        ["Simon Scrambles"] = "Simon Scrambles",
        ["Simon Screams"] = "Simon Screams",
        ["Simon Sends"] = "Simon Sends",
        ["Simon Shrieks"] = "Simon Shrieks",
        ["Simon Sings"] = "Simon Sings",
        ["Simon Sounds"] = "Simon Sounds",
        ["Simon Speaks"] = "Simon Speaks",
        ["Simon Spins"] = "Simon Spins",
        ["Simon Squawks"] = "Simon Squawks",
        ["needy Simon Squawks"] = "Simon Squawks",
        ["Simon States"] = "Simon States",
        ["Simon's Sequence"] = "Simon's Sequence",
        ["needy Simon's Sequence"] = "Simon's Sequence",
        ["Simon's Stages"] = "Simon's Stages",
        ["Simon's Star"] = "Simon's Star",
        ["Sink"] = "Sink",
        ["Skewed Slots"] = "Skewed Slots",
        ["Skinny Wires"] = "Skinny Wires",
        ["Skyrim"] = "Skyrim",
        ["Snap!"] = "Snap!",
        ["needy Snap!"] = "Snap!",
        ["Snooker"] = "Snooker",
        ["Sonic & Knuckles"] = "Sonic & Knuckles",
        ["Sonic the Hedgehog"] = "Sonic the Hedgehog",
        ["Souvenir"] = "Souvenir",
        ["Speak English"] = "Speak English",
        ["The Sphere"] = "The Sphere",
        ["Sphere"] = "The Sphere",
        ["Spinning Buttons"] = "Spinning Buttons",
        ["Splitting The Loot"] = "Splitting The Loot",
        ["Square Button"] = "Square Button",
        ["Stack'em"] = "Stack'em",
        ["The Stare"] = "The Stare",
        ["Stare"] = "The Stare",
        ["The Stock Market"] = "The Stock Market",
        ["Stock Market"] = "The Stock Market",
        ["The Stopwatch"] = "The Stopwatch",
        ["Stopwatch"] = "The Stopwatch",
        ["Street Fighter"] = "Street Fighter",
        ["Subscribe to Pewdiepie"] = "Subscribe to Pewdiepie",
        ["Subways"] = "Subways",
        ["Sueet Wall"] = "Sueet Wall",
        ["The Sun"] = "The Sun",
        ["Sun"] = "The Sun",
        ["Superlogic"] = "Superlogic",
        ["The Swan"] = "The Swan",
        ["Swan"] = "The Swan",
        ["The Switch"] = "The Switch",
        ["Switch"] = "The Switch",
        ["Switches"] = "Switches",
        ["Symbol Cycle"] = "Symbol Cycle",
        ["Symbolic Coordinates"] = "Symbolic Coordinates",
        ["Symbolic Password"] = "Symbolic Password",
        ["SYNC one two five three"] = "SYNC-125 [3]",
        ["Synchronization"] = "Synchronization",
        ["Synonyms"] = "Synonyms",
        ["Tangrams"] = "Tangrams",
        ["Tap Code"] = "Tap Code",
        ["Tasha Squeals"] = "Tasha Squeals",
        ["Tax Returns"] = "Tax Returns",
        ["Ten-Button Color Code"] = "Ten-Button Color Code",
        ["Tennis"] = "Tennis",
        ["Tetris"] = "Tetris",
        ["needy Tetris"] = "Tetris",
        ["Text Field"] = "Text Field",
        ["Third Base"] = "Third Base",
        ["Tic Tac Toe"] = "Tic Tac Toe",
        ["The Time Keeper"] = "The Time Keeper",
        ["Time Keeper"] = "The Time Keeper",
        ["Timezone"] = "Timezone",
        ["Timing is Everything"] = "Timing is Everything",
        ["The Triangle"] = "The Triangle",
        ["Triangle"] = "The Triangle",
        ["The Troll"] = "The Troll",
        ["Troll"] = "The Troll",
        ["Turn The Key"] = "Turn The Key",
        ["Turn The Keys"] = "Turn The Keys",
        ["Turtle Robot"] = "Turtle Robot",
        ["Two Bits"] = "Two Bits",
        ["T-Words"] = "T-Words",
        ["Uncolored Squares"] = "Uncolored Squares",
        ["Unfair Cipher"] = "Unfair Cipher",
        ["Unrelated Anagrams"] = "Unrelated Anagrams",
        ["USA Maze"] = "USA Maze",
        ["Valves"] = "Valves",
        ["Varicolored Squares"] = "Varicolored Squares",
        ["Venting Gas"] = "Venting Gas",
        ["needy Venting Gas"] = "Venting Gas",
        ["Visual Impairment"] = "Visual Impairment",
        ["Waste Management"] = "Waste Management",
        ["Wavetapping"] = "Wavetapping",
        ["Web Design"] = "Web Design",
        ["Westeros"] = "Westeros",
        ["Who's on First"] = "Who's on First",
        ["Who's That Monsplode?"] = "Who's That Monsplode?",
        ["Wingdings"] = "Wingdings",
        ["needy Wingdings"] = "Wingdings",
        ["The Wire"] = "The Wire",
        ["Wire"] = "The Wire",
        ["Wire Placement"] = "Wire Placement",
        ["Wire Sequence"] = "Wire Sequence",
        ["Wire Spaghetti"] = "Wire Spaghetti",
        ["Wires"] = "Wires",
        ["The Witness"] = "The Witness",
        ["Witness"] = "The Witness",
        ["Word Scramble"] = "Word Scramble",
        ["Word Search"] = "Word Search",
        ["X01"] = "X01",
        ["X O 1"] = "X01",
        ["X-Ray"] = "X-Ray",
        ["Yahtzee"] = "Yahtzee",
        ["Zoni"] = "Zoni",
        ["Zoo"] = "Zoo",
    };

    private static readonly Dictionary<string, string> _positions = new()
    {
        ["101 Dalmatians"] = "I15",
        ["3D Maze"] = "N3",
        ["3D Tunnels"] = "F13",
        ["aa"] = "N20",
        ["Accumulation"] = "K14",
        ["Adjacent Letters"] = "T4",
        ["Adventure Game"] = "C3",
        ["Air Traffic Controller"] = "E18",
        ["Alchemy"] = "K17",
        ["Algebra"] = "Q8",
        ["Alpha"] = "R20",
        ["Alphabet"] = "L4",
        ["Alphabet Numbers"] = "L12",
        ["Alphabetical Order"] = "K18",
        ["Anagrams"] = "D2",
        ["Answering Questions"] = "M2",
        ["Astrology"] = "T2",
        ["Backgrounds"] = "C9",
        ["Bartending"] = "Q17",
        ["Bases"] = "F14",
        ["Battleship"] = "I5",
        ["Benedict Cumberbatch"] = "O13",
        ["Big Circle"] = "I7",
        ["Binary LEDs"] = "N6",
        ["Binary Puzzle"] = "R16",
        ["Binary Tree"] = "B12",
        ["Bitmaps"] = "R4",
        ["Bitwise Operations"] = "J6",
        ["Black Hole"] = "E12",
        ["Blackjack"] = "I14",
        ["Blind Alley"] = "M4",
        ["Blind Maze"] = "B9",
        ["Blockbusters"] = "E15",
        ["Boggle"] = "R13",
        ["Boolean Maze"] = "T13",
        ["Boolean Venn Diagram"] = "O6",
        ["Braille"] = "F8",
        ["British Slang"] = "M12",
        ["Broken Buttons"] = "D5",
        ["Broken Guitar Chords"] = "S16",
        ["The Bulb"] = "K4",
        ["Burger Alarm"] = "O19",
        ["Burglar Alarm"] = "P9",
        ["The Button"] = "N1",
        ["Button Masher"] = "C7",
        ["Button Sequence"] = "P8",
        ["Caesar Cipher"] = "T3",
        ["Calendar"] = "T11",
        ["Capacitor Discharge"] = "M1",
        ["Catchphrase"] = "D15",
        ["Challenge & Contact"] = "Q15",
        ["Character Shift"] = "B13",
        ["Cheap Checkout"] = "N5",
        ["Chess"] = "L3",
        ["Chord Qualities"] = "C6",
        ["Christmas Presents"] = "A16",
        ["The Clock"] = "G6",
        ["The Code"] = "H11",
        ["Coffeebucks"] = "D14",
        ["Color Decoding"] = "K10",
        ["Color Generator"] = "T7",
        ["Color Match"] = "M16",
        ["Color Math"] = "S5",
        ["Color Morse"] = "E7",
        ["Colored Keys"] = "I20",
        ["Colored Squares"] = "S4",
        ["Colored Switches"] = "K7",
        ["Colorful Insanity"] = "S18",
        ["Colorful Madness"] = "E14",
        ["Colour Flash"] = "O1",
        ["Combination Lock"] = "E2",
        ["Command Prompt"] = "S13",
        ["Complex Keypad"] = "O11",
        ["Complicated Buttons"] = "H5",
        ["Complicated Wires"] = "L1",
        ["Connection Check"] = "P2",
        ["Connection Device"] = "Q14",
        ["Cookie Jars"] = "J17",
        ["Cooking"] = "P10",
        ["Coordinates"] = "O5",
        ["Countdown"] = "C15",
        ["Crackbox"] = "I16",
        ["Crazy Talk"] = "B3",
        ["Creation"] = "D6",
        ["Cruel Countdown"] = "B15",
        ["Cruel Piano Keys"] = "H3",
        ["Cryptography"] = "K3",
        ["The Crystal Maze"] = "A15",
        ["The Cube"] = "S10",
        ["Curriculum"] = "E8",
        ["Cursed Double-Oh"] = "H16",
        ["Decolored Squares"] = "B18",
        ["Determinants"] = "Q12",
        ["DetoNATO"] = "D18",
        ["The Digit"] = "M14",
        ["Digit String"] = "Q20",
        ["Digital Cipher"] = "L19",
        ["Digital Root"] = "C11",
        ["Discolored Squares"] = "D17",
        ["Divided Squares"] = "P14",
        ["Dominoes"] = "B17",
        ["Double Color"] = "N12",
        ["Double-Oh"] = "M5",
        ["Dr. Doctor"] = "T10",
        ["Dragon Energy"] = "D13",
        ["Draw"] = "M19",
        ["Edgework"] = "I6",
        ["Elder Futhark"] = "H19",
        ["Emoji Math"] = "S1",
        ["Encrypted Morse"] = "T14",
        ["English Test"] = "O4",
        ["Equations"] = "P12",
        ["Error Codes"] = "S9",
        ["European Travel"] = "R9",
        ["Extended Password"] = "D8",
        ["Factory Maze"] = "Q16",
        ["Fast Math"] = "K6",
        ["Faulty Backgrounds"] = "F9",
        ["The Festive Jukebox"] = "N16",
        ["Festive Piano Keys"] = "H8",
        ["The Fidget Spinner"] = "M18",
        ["Filibuster"] = "F2",
        ["FizzBuzz"] = "F6",
        ["Flags"] = "I8",
        ["Flashing Lights"] = "E13",
        ["Flavor Text"] = "T17",
        ["Flavor Text EX"] = "A18",
        ["Flip The Coin"] = "E17",
        ["Follow the Leader"] = "I4",
        ["Font Select"] = "C10",
        ["Foreign Exchange Rates"] = "L2",
        ["Forget Everything"] = "I10",
        ["Forget Me Not"] = "R2",
        ["Forget This"] = "K19",
        ["Four-Card Monte"] = "M20",
        ["Free Parking"] = "I17",
        ["Friendship"] = "J4",
        ["Functions"] = "C16",
        ["Gadgetron Vendor"] = "T18",
        ["Game of Life Cruel"] = "N7",
        ["Game of Life Simple"] = "O7",
        ["The Gamepad"] = "D4",
        ["Genetic Sequence"] = "F19",
        ["The Giant's Drink"] = "P20",
        ["Graffiti Numbers"] = "D11",
        ["Graphic Memory"] = "A20",
        ["Greek Calculus"] = "M11",
        ["Grid Matching"] = "J10",
        ["Gridlock"] = "H7",
        ["Grocery Store"] = "N19",
        ["Guitar Chords"] = "S11",
        ["The Hangover"] = "P16",
        ["Harmony Sequence"] = "P18",
        ["Hex To Decimal"] = "R6",
        ["The Hexabutton"] = "D19",
        ["Hexamaze"] = "Q4",
        ["Hidden Colors"] = "T20",
        ["Hieroglyphics"] = "B16",
        ["Hogwarts"] = "A17",
        ["Homophones"] = "C18",
        ["Horrible Memory"] = "Q13",
        ["Hot Potato"] = "T15",
        ["HTTP Response"] = "Q5",
        ["Human Resources"] = "N9",
        ["Hunting"] = "C8",
        ["The Hypercube"] = "E20",
        ["Ice Cream"] = "Q6",
        ["Identity Parade"] = "T8",
        ["IKEA"] = "F15",
        ["Instructions"] = "R14",
        ["The iPhone"] = "K9",
        ["The Jack-O'-Lantern"] = "N14",
        ["The Jewel Vault"] = "B11",
        ["The Jukebox"] = "S8",
        ["Keypad"] = "K1",
        ["Knob"] = "J1",
        ["Know Your Way"] = "S12",
        ["Krazy Talk"] = "F17",
        ["Kudosudoku"] = "L15",
        ["The Labyrinth"] = "K16",
        ["Lasers"] = "Q11",
        ["Laundry"] = "F5",
        ["LED Encryption"] = "H6",
        ["LED Grid"] = "I9",
        ["LED Math"] = "J18",
        ["Left and Right"] = "B19",
        ["LEGOs"] = "A10",
        ["Letter Keys"] = "Q2",
        ["Light Cycle"] = "P5",
        ["Lights Out"] = "T1",
        ["Lightspeed"] = "D12",
        ["Lion's Share"] = "G14",
        ["Listening"] = "K2",
        ["Logic"] = "A3",
        ["Logic Gates"] = "H10",
        ["Logical Buttons"] = "G11",
        ["Lombax Cubes"] = "S19",
        ["The London Underground"] = "G10",
        ["Mad Memory"] = "O17",
        ["Mafia"] = "G8",
        ["Mahjong"] = "K15",
        ["Maintenance"] = "A9",
        ["Manometers"] = "J13",
        ["Marble Tumble"] = "E11",
        ["Maritime Flags"] = "O12",
        ["Mashematics"] = "E9",
        ["Mastermind Cruel"] = "F7",
        ["Mastermind Simple"] = "G7",
        ["Math"] = "R1",
        ["Maze"] = "I1",
        ["Maze Scrambler"] = "J12",
        ["Mega Man 2"] = "R19",
        ["Melody Sequencer"] = "R18",
        ["Memory"] = "H1",
        ["Microcontroller"] = "B4",
        ["Micro-Modules"] = "G19",
        ["Mineseeker"] = "I12",
        ["Minesweeper"] = "L6",
        ["Modern Cipher"] = "H9",
        ["Module Homework"] = "N13",
        ["Module Maze"] = "I19",
        ["Modules Against Humanity"] = "G5",
        ["Modulo"] = "N15",
        ["Monsplode Trading Cards"] = "M7",
        ["Monsplode, Fight!"] = "G4",
        ["The Moon"] = "R10",
        ["Morse Code"] = "G1",
        ["Morse Identification"] = "H18",
        ["Morse War"] = "G12",
        ["Morse-A-Maze"] = "J7",
        ["Morsematics"] = "O2",
        ["Mortal Kombat"] = "D9",
        ["Motion Sense"] = "G2",
        ["Mouse In The Maze"] = "M3",
        ["Murder"] = "C4",
        ["Mystic Square"] = "F3",
        ["The Necronomicon"] = "L20",
        ["Needy Mrs Bob"] = "E16",
        ["Neutralization"] = "A6",
        ["Nonogram"] = "P7",
        ["The Number"] = "O10",
        ["The Number Cipher"] = "K12",
        ["Number Nimbleness"] = "O15",
        ["Number Pad"] = "P3",
        ["Numbers"] = "G17",
        ["Only Connect"] = "T5",
        ["Orientation Cube"] = "N2",
        ["Painting"] = "S7",
        ["Party Time"] = "J14",
        ["Passport Control"] = "A19",
        ["Password"] = "F1",
        ["Pattern Cube"] = "R12",
        ["Pay Respects"] = "P15",
        ["Periodic Table"] = "H15",
        ["Perplexing Wires"] = "L7",
        ["Perspective Pegs"] = "A4",
        ["Piano Keys"] = "P1",
        ["Pie"] = "E10",
        ["Pigpen Rotations"] = "I18",
        ["Planets"] = "K20",
        ["Playfair Cipher"] = "M10",
        ["Plumbing"] = "G3",
        ["The Plunger"] = "E19",
        ["The Plunger Button"] = "L14",
        ["Poetry"] = "O8",
        ["Point of Order"] = "P6",
        ["Poker"] = "M8",
        ["Polyhedral Maze"] = "K8",
        ["Press X"] = "Q9",
        ["Probing"] = "Q3",
        ["Purgatory"] = "Q19",
        ["QR Code"] = "B7",
        ["Question Mark"] = "R17",
        ["Quintuples"] = "B14",
        ["Quiz Buzz"] = "C20",
        ["Radiator"] = "G9",
        ["The Radio"] = "M15",
        ["Random Number Generator"] = "D7",
        ["Rapid Buttons"] = "T9",
        ["Refill that Beer!"] = "R7",
        ["Regular Crazy Talk"] = "T16",
        ["Resistors"] = "R3",
        ["Retirement"] = "G15",
        ["Reverse Morse"] = "I13",
        ["Rhythms"] = "R5",
        ["Rock Paper Scissors Lizard Spock"] = "P4",
        ["Rotary Phone"] = "S2",
        ["Round Keypad"] = "J2",
        ["Rubik's Clock"] = "B10",
        ["Rubik's Cube"] = "E6",
        ["S.E.T."] = "Q7",
        ["Safety Safe"] = "I3",
        ["Schlag den Bomb"] = "J15",
        ["The Screw"] = "S6",
        ["Scripting"] = "D16",
        ["Sea Shells"] = "N4",
        ["Semaphore"] = "Q1",
        ["Seven Wires"] = "H20",
        ["Shape Memory"] = "A8",
        ["Shape Shift"] = "H4",
        ["Shapes And Bombs"] = "S17",
        ["Shikaku"] = "K13",
        ["Signals"] = "P13",
        ["Silly Slots"] = "O3",
        ["Simon Samples"] = "A13",
        ["Simon Says"] = "E1",
        ["Simon Scrambles"] = "O18",
        ["Simon Screams"] = "E5",
        ["Simon Sends"] = "K11",
        ["Simon Shrieks"] = "N11",
        ["Simon Sings"] = "J11",
        ["Simon Sounds"] = "L18",
        ["Simon Speaks"] = "C17",
        ["Simon Spins"] = "F16",
        ["Simon Squawks"] = "M17",
        ["Simon States"] = "I2",
        ["Simon's Sequence"] = "N18",
        ["Simon's Stages"] = "H17",
        ["Simon's Star"] = "F12",
        ["Sink"] = "J9",
        ["Skewed Slots"] = "S3",
        ["Skinny Wires"] = "O16",
        ["Skyrim"] = "O9",
        ["Snap!"] = "S20",
        ["Snooker"] = "H14",
        ["Sonic & Knuckles"] = "A14",
        ["Sonic the Hedgehog"] = "N8",
        ["Souvenir"] = "B5",
        ["Speak English"] = "F20",
        ["The Sphere"] = "C14",
        ["Spinning Buttons"] = "L16",
        ["Splitting The Loot"] = "T12",
        ["Square Button"] = "H2",
        ["Stack'em"] = "G20",
        ["The Stare"] = "T19",
        ["The Stock Market"] = "H12",
        ["The Stopwatch"] = "D10",
        ["Street Fighter"] = "J16",
        ["Subscribe to Pewdiepie"] = "P19",
        ["Subways"] = "P11",
        ["Sueet Wall"] = "S15",
        ["The Sun"] = "L10",
        ["Superlogic"] = "Q10",
        ["The Swan"] = "L9",
        ["The Switch"] = "H13",
        ["Switches"] = "A2",
        ["Symbol Cycle"] = "B8",
        ["Symbolic Coordinates"] = "L8",
        ["Symbolic Password"] = "K5",
        ["SYNC-125 [3]"] = "F18",
        ["Synchronization"] = "G13",
        ["Synonyms"] = "L11",
        ["Tangrams"] = "N10",
        ["Tap Code"] = "I11",
        ["Tasha Squeals"] = "J19",
        ["Tax Returns"] = "A11",
        ["Ten-Button Color Code"] = "G16",
        ["Tennis"] = "M13",
        ["Tetris"] = "J3",
        ["Text Field"] = "J5",
        ["Third Base"] = "A5",
        ["Tic Tac Toe"] = "E4",
        ["The Time Keeper"] = "C12",
        ["Timezone"] = "J8",
        ["Timing is Everything"] = "B20",
        ["The Triangle"] = "R15",
        ["The Troll"] = "J20",
        ["Turn The Key"] = "E3",
        ["Turn The Keys"] = "D3",
        ["Turtle Robot"] = "R11",
        ["Two Bits"] = "B2",
        ["T-Words"] = "O14",
        ["Uncolored Squares"] = "C13",
        ["Unfair Cipher"] = "Q18",
        ["Unrelated Anagrams"] = "P17",
        ["USA Maze"] = "A12",
        ["Valves"] = "S14",
        ["Varicolored Squares"] = "L17",
        ["Venting Gas"] = "D1",
        ["Visual Impairment"] = "R8",
        ["Waste Management"] = "M9",
        ["Wavetapping"] = "D20",
        ["Web Design"] = "B6",
        ["Westeros"] = "G18",
        ["Who's on First"] = "C1",
        ["Who's That Monsplode?"] = "F4",
        ["Wingdings"] = "C19",
        ["The Wire"] = "F10",
        ["Wire Placement"] = "L5",
        ["Wire Sequence"] = "A1",
        ["Wire Spaghetti"] = "L13",
        ["Wires"] = "B1",
        ["The Witness"] = "O20",
        ["Word Scramble"] = "C2",
        ["Word Search"] = "C5",
        ["X01"] = "F11",
        ["X-Ray"] = "A7",
        ["Yahtzee"] = "T6",
        ["Zoni"] = "N17",
        ["Zoo"] = "M6",
    };

    private static readonly int[][] _connections =
    [
        [1],
        [21],
        [3, 22],
        [],
        [5, 24],
        [],
        [7],
        [8],
        [9, 28],
        [],
        [11, 30],
        [12, 31],
        [13],
        [14],
        [15],
        [16, 35],
        [],
        [18, 37],
        [19],
        [],
        [21, 40],
        [41],
        [23, 42],
        [],
        [25],
        [26],
        [46],
        [47],
        [29],
        [30, 49],
        [],
        [51],
        [33, 52],
        [34],
        [],
        [36, 55],
        [],
        [38],
        [39, 58],
        [],
        [60],
        [42],
        [43],
        [44],
        [45, 64],
        [65],
        [47, 66],
        [67],
        [49, 68],
        [],
        [51, 70],
        [52],
        [53],
        [54, 73],
        [55, 74],
        [],
        [57, 76],
        [77],
        [59, 78],
        [],
        [61, 80],
        [62],
        [63, 82],
        [64],
        [],
        [66],
        [],
        [68, 87],
        [],
        [89],
        [],
        [72, 91],
        [73],
        [],
        [75, 94],
        [76],
        [],
        [78],
        [98],
        [99],
        [100],
        [101],
        [102],
        [84, 103],
        [],
        [105],
        [87],
        [107],
        [89, 108],
        [90, 109],
        [110],
        [111],
        [93, 112],
        [94],
        [],
        [96, 115],
        [97, 116],
        [],
        [118],
        [119],
        [120],
        [121],
        [122],
        [104],
        [105],
        [106],
        [107, 126],
        [127],
        [128],
        [],
        [111, 130],
        [131],
        [113, 132],
        [],
        [115, 134],
        [],
        [117],
        [],
        [119],
        [139],
        [140],
        [141],
        [142],
        [124, 143],
        [125],
        [145],
        [146],
        [128],
        [129, 148],
        [149],
        [150],
        [151],
        [133, 152],
        [],
        [135, 154],
        [],
        [156],
        [157],
        [139, 158],
        [],
        [141, 160],
        [],
        [143],
        [144, 163],
        [],
        [146],
        [],
        [148, 167],
        [],
        [169],
        [170],
        [152],
        [153, 172],
        [],
        [155, 174],
        [156, 175],
        [157],
        [158],
        [159, 178],
        [179],
        [161],
        [181],
        [163],
        [164],
        [184],
        [166, 185],
        [167],
        [],
        [169, 188],
        [],
        [190],
        [172, 191],
        [173],
        [174],
        [],
        [176],
        [177],
        [197],
        [],
        [199],
        [181],
        [182, 201],
        [202],
        [184, 203],
        [185, 204],
        [186],
        [206],
        [188],
        [189],
        [209],
        [191],
        [211],
        [212],
        [194, 213],
        [],
        [196, 215],
        [197],
        [198, 217],
        [218],
        [219],
        [201],
        [221],
        [222],
        [223],
        [205, 224],
        [],
        [207],
        [208, 227],
        [209],
        [210],
        [211],
        [212, 231],
        [213],
        [214, 233],
        [215],
        [],
        [217, 236],
        [],
        [238],
        [239],
        [240],
        [241],
        [223],
        [],
        [225],
        [245],
        [246],
        [247],
        [229],
        [230, 249],
        [],
        [251],
        [252],
        [234],
        [],
        [255],
        [237, 256],
        [257],
        [239],
        [259],
        [241, 260],
        [261],
        [262],
        [244],
        [245],
        [246],
        [247],
        [267],
        [268],
        [250, 269],
        [251],
        [252, 271],
        [272],
        [254, 273],
        [],
        [256, 275],
        [],
        [277],
        [278],
        [279],
        [280],
        [262],
        [263, 282],
        [264],
        [284],
        [266],
        [267, 286],
        [287],
        [269, 288],
        [],
        [271],
        [],
        [292],
        [274, 293],
        [],
        [276, 295],
        [296],
        [297],
        [279, 298],
        [],
        [281],
        [282],
        [283, 302],
        [284],
        [304],
        [305],
        [306],
        [307],
        [308],
        [309],
        [291, 310],
        [292],
        [],
        [294, 313],
        [295],
        [],
        [316],
        [],
        [299, 318],
        [],
        [301],
        [302],
        [322],
        [304],
        [305],
        [306, 325],
        [326],
        [308],
        [328],
        [310, 329],
        [311, 330],
        [312, 331],
        [313],
        [],
        [315, 334],
        [316],
        [336],
        [318, 337],
        [319],
        [339],
        [321],
        [322, 341],
        [],
        [324, 343],
        [325],
        [],
        [327],
        [347],
        [329],
        [349],
        [350],
        [332],
        [333],
        [334],
        [335],
        [355],
        [337],
        [338],
        [358],
        [],
        [341],
        [361],
        [343],
        [344],
        [345, 364],
        [346],
        [347],
        [348, 367],
        [349],
        [369],
        [370],
        [371],
        [353, 372],
        [354],
        [],
        [375],
        [357, 376],
        [377],
        [359, 378],
        [],
        [361],
        [362],
        [363, 382],
        [364],
        [365],
        [366, 385],
        [386],
        [387],
        [369, 388],
        [389],
        [390],
        [372, 391],
        [373],
        [374],
        [],
        [395],
        [396],
        [378],
        [379],
        [399],
        [381],
        [382],
        [],
        [384],
        [385],
        [],
        [387],
        [],
        [],
        [390],
        [391],
        [392],
        [393],
        [394],
        [395],
        [396],
        [397],
        [],
        [399],
        []
    ];

}
